package com.appdynamics.monitors.informatica.metadata;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "MetadataService", targetNamespace = "http://www.informatica.com/wsh", wsdlLocation = "file:/Users/akshay.srivastava/AppDynamics/InformaticaExtension/MetadataWSDL.xml")
public class MetadataService
        extends Service {

    private final static URL METADATASERVICE_WSDL_LOCATION;
    private final static WebServiceException METADATASERVICE_EXCEPTION;
    private final static QName METADATASERVICE_QNAME = new QName("http://www.informatica.com/wsh", "MetadataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/akshay.srivastava/AppDynamics/InformaticaExtension/MetadataWSDL.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METADATASERVICE_WSDL_LOCATION = url;
        METADATASERVICE_EXCEPTION = e;
    }

    public MetadataService() {
        super(__getWsdlLocation(), METADATASERVICE_QNAME);
    }

    public MetadataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), METADATASERVICE_QNAME, features);
    }

    public MetadataService(URL wsdlLocation) {
        super(wsdlLocation, METADATASERVICE_QNAME);
    }

    public MetadataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METADATASERVICE_QNAME, features);
    }

    public MetadataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetadataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (METADATASERVICE_EXCEPTION != null) {
            throw METADATASERVICE_EXCEPTION;
        }
        return METADATASERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns MetadataInterface
     */
    @WebEndpoint(name = "Metadata")
    public MetadataInterface getMetadata() {
        return super.getPort(new QName("http://www.informatica.com/wsh", "Metadata"), MetadataInterface.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns MetadataInterface
     */
    @WebEndpoint(name = "Metadata")
    public MetadataInterface getMetadata(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.informatica.com/wsh", "Metadata"), MetadataInterface.class, features);
    }

}
